### PR TITLE
Fix SHELLEXECUTEINFO object and hProcess handle leak on Windows

### PR DESCRIPTION
**Pull request by poiru**
The `SHELLEXECUTEINFO` object was previously allocated on the heap and
never freed. We now use the stack instead to fix this memory leak.

The `SHELLEXECUTEINFO.hProcess` handle is supposed to be closed manually
when the `SEE_MASK_NOCLOSEPROCESS` flag is used. We now close the
handle after we're done with it.

### CODE REVIEW

**Comment by poiru** [comment]
cc @maxbrunsfeld

**Comment by poiru** [comment]
@darangi This is still relevant, can you take a look please?

**Comment by darangi** [comment]
Hi @poiru, we will take a look 😃

**Review by maxbrunsfeld — APPROVED** [review]
This all looks good to me. Thanks!

**Comment by darangi** [comment]
Thanks for the contributions 🙇‍♂️  @poiru

**Pull request merged**
